### ISSUE TITLE
 ERROR  kill ESRCH  

### ISSUE THREAD

**Issue by AppLetico** [dwyl/terminate#49]
Terminate has worked pretty well so far in testing, but I did see this error today and had to kill the process manually :(

Any idea what may have caused this?  I am testing locally on a macbook with node v14.16.1

```
 ERROR  kill ESRCH                                                                                                                                                23:14:48

  at process.kill (internal/process/per_thread.js:200:13)
  at handlePsTreeCallback (node_modules/terminate/handlePsTreeCallback.js:28:13)
  at node_modules/terminate/terminate.js:44:5
  at node_modules/ps-tree/index.js:87:7
  at Stream.a.end (node_modules/event-stream/index.js:87:5)
  at Stream.onend (internal/streams/legacy.js:46:10)
  at Stream.emit (events.js:327:22)
  at Stream.EventEmitter.emit (domain.js:467:12)
  at end (node_modules/map-stream/index.js:116:39)
  at Stream.stream.end (node_modules/map-stream/index.js:122:5)
```

**Comment by nelsonic** [comment]
Hi @buffaloDeveloper 👋
Thanks for opening this issue.
We’ve not seen that before.
Done a bit of Googling and it appears to be an error where the process cannot be found.

https://unix.stackexchange.com/questions/258955/what-does-esrch-mean

> **[ESRCH]**
No process or process group can be found corresponding to that specified by pid.

My guess is that it’s a short-lived process that terminates itself before you get a chance to.
If you can give more detail, we might be able to help debug. 💭

**Comment by nelsonic** [comment]
Closing as no reply. Guessing the situation resolved itself. ✅ 
If anyone else is seeing this, feel free to comment. 💬
